### ISSUE TITLE
No copy dll in the shared storage

### ISSUE THREAD

**Issue by lzianekhodja** [aneoconsulting/ArmoniK#244]
**Describe the bug**

The case where we miss to copy the dll in the shared storage.

**To Reproduce**
1. Deploy ArmoniK infrastructure
2. Delete the shared storage if it already exists (ex: ${HOME}/data/)
3. Launch the test of [symphony like ](https://github.com/aneoconsulting/ArmoniK.Samples/blob/main/tools/tests/symphony_like.sh) as follows:
```bash
./symphony_like.sh -no-copy-dll -e <CONTROL_PLANE_URL> pTask 1
```
such as <CONTROL_PLANE_URL> is the endpoint url of control plane (ex: http://192.168.1.13:5001)

4. the test runs endlessly (cannot get results)

**Expected behavior**

Display an error saying that the dll is missing

**Screenshots**

the test runs endlessly (cannot get results) without errors as follows:

![expected](https://user-images.githubusercontent.com/85945328/173104292-dab5471a-fd48-4625-80dd-23fb39662fc6.png)

**Infra**
- Target (Local, AWS, Docker compose, etc..) : Local
- Queue (Activemq managed or not) : not managed ActiveMQ
- DataBase (MongoDB) : not managed MongoDB
- Cache (Redis managed or not) : not managed Redis
- Infra Version : 2.7.3
- Core Images and Version (if known) : 0.5.11
- Worker Image and Version (if known) : 0.5.10

**Additional context**

The same behavior occurs in AWS infrastructure (no copy to S3 bucket).

**Comment by dbrasseur-aneo** [comment]
Problem occurs with core 0.5.12 and worker 0.5.12 as well, but log is present in seq when tested locally.
Problem is fixed with core 0.5.14 and worker 0.6.1.
The client raises an AggregateException with "Error in task 742ffed9-52c8-4ca9-a2b9-2a21a90d0221 Fail to copy ArmoniK.Samples.SymphonyPackage-v2.0.0.zip"

**Comment by lzianekhodja** [comment]
The problem persists on the version of AWS (the shared storage is a S3 bucket):

![warning](https://user-images.githubusercontent.com/85945328/175521152-996f5d61-8632-4b6e-8608-c497d1fcc38f.png)

![error](https://user-images.githubusercontent.com/85945328/175521170-e8d400d8-2f4c-48bf-ab49-9319c6a0dbdb.png)

![client](https://user-images.githubusercontent.com/85945328/175521204-ca809ee9-1614-4a9a-aff3-fb01ef2474c4.png)

**Comment by ngruelaneo** [comment]
See #276
